### ISSUE TITLE
How work Archive?

### ISSUE THREAD

**Issue by zarevskaya** [DCsunset/LFReader#1]
Hello, 

when I make archives, I don't see where they are? 
The folder remains empty. I'm using Docker. 

Thanks in advance.

**Comment by DCsunset** [comment]
There was a bug in v2.2.0 that caused the data to be stored in `/app/backend` directory in the container (`db.sqlite` and `archives`).
It should have been fixed in v2.2.1, in which data is stored at `/app/data`.

To migrate your existing data, you can move the data files out of the container and mount it back in a new container of v2.2.1.

**Comment by zarevskaya** [comment]
Thanks
